version: 5.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: HL7-dotnetcore.sln

after_build:
  - ps: .\nuget\pack.ps1

test: off

artifacts:
  - path: src\bin\Release\HL7-dotnetcore.dll
    name: HL7-dotnetcore.dll
  - path: '**\*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: R6heOdfhVtvSfLDkqek6em1JZtuKurosU0H1CtHMMN4ueDqVOYAUNecR1BI70nFb
  artifact: /.*\.nupkg/
  
  
  